# Generated by Django 5.1.5 on 2026-07-07 00:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_playerstats_guestlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSettings',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('control_profile', models.CharField(blank=True, choices=[('mouse', 'mouse'), ('keyboard', 'keyboard'), ('touch', 'touch')], default='', max_length=16)),
                ('volume_master', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('volume_sfx', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('fullscreen_pref', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_player_settings',
            },
        ),
    ]
