# Generated by Django 5.1.5 on 2026-07-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_playersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='agilidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='forca',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='vitalidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
