# Generated by Django 5.1.5 on 2026-07-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('xp_multiplier', models.FloatField(blank=True, null=True)),
                ('coin_multiplier', models.FloatField(blank=True, null=True)),
                ('flag_enabled', models.BooleanField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gameops_game_event',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80)),
                ('flag_enabled', models.BooleanField(default=True)),
                ('xp_multiplier', models.FloatField(default=1.0)),
                ('coin_multiplier', models.FloatField(default=1.0)),
                ('expected_players', models.PositiveIntegerField(default=8)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gameops_room_config',
            },
        ),
        migrations.CreateModel(
            name='RoomConfigMapRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('map_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.mapentry')),
                ('room_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_entries', to='gameops.roomconfig')),
            ],
            options={
                'db_table': 'gameops_room_config_map_rotation',
                'ordering': ['order'],
                'unique_together': {('room_config', 'order')},
            },
        ),
        migrations.AddField(
            model_name='roomconfig',
            name='map_rotation',
            field=models.ManyToManyField(related_name='room_configs', through='gameops.RoomConfigMapRotation', to='maps.mapentry'),
        ),
    ]
