# Generated by Django 5.1.5 on 2026-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(db_index=True, max_length=64)),
                ('type', models.CharField(db_index=True, max_length=32)),
                ('player_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('map_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ts', models.BigIntegerField(help_text='epoch ms — Date.now() no instante do evento (Node)')),
                ('tick', models.PositiveIntegerField()),
                ('payload', models.JSONField(help_text='evento cru completo, schema TELEMETRY_SCHEMA_VERSION')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telemetry_event',
                'ordering': ['match_id', 'tick'],
                'indexes': [models.Index(fields=['match_id', 'type'], name='telemetry_e_match_i_0c538f_idx')],
            },
        ),
    ]
