# Generated by Django 5.1.5 on 2026-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapEntry',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('author', models.CharField(blank=True, default='', max_length=80)),
                ('w', models.PositiveIntegerField()),
                ('h', models.PositiveIntegerField()),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('data', models.JSONField(help_text='MapFileV1 completo — idêntico ao maps/<id>.map.json')),
                ('is_active', models.BooleanField(default=True)),
                ('in_rotation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maps_map_entry',
                'ordering': ['id'],
            },
        ),
    ]
